version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - /home/radmin/mysql-volume-1:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network
    depends_on:
      - mysql

  ghostsab:
    #image: ghost:latest
    image: rmaurodev/ghost:1
    #build: .
    restart: always
    ports:
      - 8081:2054
    environment:
      url: ${APP_PUBLIC_URL_SAB}
      APP_PUBLIC_URL: ${APP_PUBLIC_URL_SAB}
      MYSQL_DATABASE_URL: ${MYSQL_DATABASE_URL_SAB}
      CLOUDINARY_URL: ${CLOUDINARY_URL_SAB}
      SENDGRID_LOGIN: ${SENDGRID_LOGIN}
      SENDGRID_PASSWORD: ${SENDGRID_PASSWORD}
      NODE_ENV: ${NODE_ENV_SAB}
      PORT: 2054
    volumes:
      - /home/radmin/ghost-volume-sab:/app/content/themes
    networks:
      - mysql-compose-network
    depends_on:
      - mysql
  
  ghostrmauro:
    #image: ghost:latest
    image: rmaurodev/ghost:1
    #build: .
    restart: always
    ports:
      - 80:2054
    environment:
      url: ${APP_PUBLIC_URL_RMAURO}
      APP_PUBLIC_URL: ${APP_PUBLIC_URL_RMAURO}
      MYSQL_DATABASE_URL: ${MYSQL_DATABASE_URL_RMAURO}
      CLOUDINARY_URL: ${CLOUDINARY_URL_RMAURO}
      SENDGRID_LOGIN: ${SENDGRID_LOGIN}
      SENDGRID_PASSWORD: ${SENDGRID_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      PORT: 2054
    volumes:
      - /home/radmin/ghost-volume-rmauro:/app/content/themes
    networks:
      - mysql-compose-network
    depends_on:
      - mysql

networks: 
  mysql-compose-network:
    driver: bridge
